config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    
        #Courses
    path("courses/", include("justpython.content.urls", namespace="content")),
    path("blog/", include("justpython.topic.urls", namespace="topic")),
    # Added CKEditor 5 URLs here
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    # User management
    path("users/", include("justpython.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

justpython/content/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, VideoDetailView

app_name = "content"

urlpatterns = [
    path("", CourseListView.as_view(), name='course-list'),
    path("<slug>/", CourseDetailView.as_view(), name='course-detail'),
    path("<slug>/<video_slug>/", VideoDetailView.as_view(), name='video-detail'),
]

justpython/topic/urls.py
from django.urls import path
from .views import CategoryListView, CategoryDetailView, PostDetailView

app_name = "topic"

urlpatterns = [
      path('', CategoryListView.as_view(), name='topic-list'),
      path('<slug>/', CategoryDetailView.as_view(), name='post-list'),
      path('<slug>/<post_slug>', PostDetailView.as_view(), name='post-detail'),
]

justpython/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

justpython/content/models.py
from django.db import models
from django.shortcuts import reverse
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.conf import settings
from django.contrib.auth import get_user_model
from allauth.account.signals import email_confirmed
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY
User = get_user_model()

# Create your models here.

class Pricing(models.Model):
    name = models.CharField(max_length=100)   # Basic / Pro / Premium  
    
    def __str__(self):
        return self.name
    
class Subscription(models.Model):
       user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
       pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE, related_name='subscriptions')
       created = models.DateTimeField(auto_now_add=True)
       stripe_subscription_id = models.CharField(max_length=50)
       status = models.CharField(max_length=100)
       
       def __str__(self):
           return self.user.email
    
class Course(models.Model):
    pricing_tiers = models.ManyToManyField(Pricing, blank=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    thumbnail = models.ImageField(upload_to="thumnails/")
    description = models.TextField()
    
    
    def __str__(self):
        return self.name    
     
    def get_absolute_url(self):
        return reverse("content:course-detail", kwargs={"slug": self.slug})
    
class Video(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='videos')  
    vimeo_id = models.CharField(max_length=20)
    title = models.CharField(max_length=150)
    timeline = models.CharField(max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    order = models.IntegerField(default=1)
    
    class Meta:
        ordering = ["order"]
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("content:video-detail", kwargs={
            "video_slug": self.slug,
            "slug": self.course.slug
            })
        
def pre_save_course(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)

def pre_save_video(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)
        
def post_email_confirmed(request, email_address, *args, **kwargs):
    user = User.objects.get(email=email_address.email)
    
    free_trial_pricing = Pricing.objects.get(name='Free Trial')
    subscription = Subscription.objects.create(
        user=user,
        pricing=free_trial_pricing
        )
    stripe_customer = stripe.Customer.create(
        email=user.email
        )
    stripe_subscription = stripe.Subscription.create(
        customer=stripe_customer["id"],
        items=[{'price': 'price_1OqNO8SHmWkafoW7bMMvUD6K'}],
        trial_period_days=7
    )
    print(stripe_subscription)
    subscription.status = stripe_subscription["status"]
    subscription.stripe_subscription_id = stripe_subscription["id"]
    subscription.save()
    # user.stripe_customer_id = stripe_customer["id"]
    # user.save()
        
        
email_confirmed.connect(post_email_confirmed)
pre_save.connect(pre_save_course, sender=Course)    
pre_save.connect(pre_save_video, sender=Video)       

justpython/topic/models.py
from django.db import models
from django.shortcuts import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field

class Category(models.Model):
    name = models.CharField(unique=False, max_length=100)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    thumbnail = models.ImageField(upload_to="thumnails/")
    description = models.TextField()
  
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('topic:post-list', kwargs={"slug": self.slug}) 
    
class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    body = CKEditor5Field(null=True, blank=True, config_name='extends')
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    order = models.IntegerField(default=1)
    
    
    class Meta:
        ordering = ["order"]

    
    
    def __str__(self):
        return self.title  
    
    def get_absolute_url(self):
        return reverse('topic:post-detail', kwargs={
            "post_slug": self.slug,
            "slug": self.category.slug
            })  
    
       
    
def set_slug_Category(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)

def set_slug_post(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)

pre_save.connect(set_slug_Category, sender=Category)    
pre_save.connect(set_slug_post, sender=Post)  

justpython/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for justpython.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

justpython/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

justpython/content/views.py
from django.views import generic
from .models import Course, Video
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import CoursePermissionMixin

# Create your views here.
class CourseListView(generic.ListView):
    template_name = "content/course_list.html"
    queryset = Course.objects.all()
    
class CourseDetailView(generic.DetailView):
    template_name = "content/course_detail.html"
    queryset = Course.objects.all()    
    
class VideoDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "content/video_detail.html"
    
    def get_context_data(self, **kwargs):
        context = super(VideoDetailView, self).get_context_data(**kwargs)
        course = self.get_course()
        subscription = self.request.user.subscription
        pricing_tier = subscription.pricing
        context.update({
            "has_permission": pricing_tier in course.pricing_tiers.all()
            
        })
        return context
    
    def get_course(self):
        return get_object_or_404(Course, slug=self.kwargs["slug"])
        
    
    def get_object(self):
        video = get_object_or_404(Video, slug=self.kwargs["video_slug"])
        return video
     
    def get_queryset(self):
        course = get_object_or_404(Course, slug=self.kwargs["slug"])
        return course.videos.all()

justpython/topic/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404
from django.views import generic
from .models import Category, Post

# Create your views here.
class CategoryListView(generic.ListView):
    template_name = 'topic/category.html'
    queryset = Category.objects.all()
    
class CategoryDetailView(generic.DetailView):
    template_name = 'topic/post.html'
    queryset = Category.objects.all()

     
class PostDetailView(generic.DetailView):
    template_name = 'topic/post_detail.html'
    
    def get_object(self):
        post = get_object_or_404(Post, slug=self.kwargs["post_slug"])
        return post
    
    
    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs["slug"])
        return category.post.all()
    

    
       

justpython/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from justpython.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

justpython/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from justpython.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

justpython/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

justpython/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}{% endblock %}| Camstock Management</title>

{% block css %}
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'icons/manifest.json' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
<link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/aos.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"/>


<link href="https://cdn.tailwindcss.com" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/bulma@0.9.3/css/bulma.min.css">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" /> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/a11y-dark.min.css" /> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/codepen-embed.min.css"/> -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/gml.min.css" /> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/srcery.min.css"/> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/base16/zenburn.min.css"/> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/base16/zenburn.min.css"/> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/SyntaxHighlighter/3.0.83/styles/shCoreEclipse.min.css" /> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/SyntaxHighlighter/3.0.83/styles/shCoreFadeToGrey.min.css" /> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.2/styles/atelier-dune.light.min.css"/> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flex-layout-attribute/1.0.3/css/flex-layout-attribute.css" integrity="sha512-TUKhSPFpY/Y/QRPMSX6FlwBlMOWtGIm0JB7CQFDVVQiRNcvpt3ggZeQb2+PqUmKTwd3pMyDlUdO6jqAk295flw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

{% endblock css %}

{% block extra_head %}
    
{% endblock extra_head %}
    
    

<body>





<!-- stating of base page -->
{% include 'navbar.html' %}
{% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
        {% endfor %}
{% endif %}

<section class="section">
    <div class="container"> 
        {% block content %}
        {% endblock content%}
    </div>
</section>

{% include 'footer.html' %}
<!-- ending of base page -->





{% block javascript %}
<script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script>hljs.highlightAll()</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Get the burger icon element
        const burger = document.querySelector('.navbar-burger');
        // Get the target element that needs to be toggled
        const menu = document.getElementById('navbarMenu');
    
        // Add an event listener to the burger icon
        burger.addEventListener('click', function () {
            // Toggle the "is-active" class on both the burger icon and the target element
            burger.classList.toggle('is-active');
            menu.classList.toggle('is-active');
        });
    });

    
</script>
<script type="text/javascript">
    function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i =0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begins with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')){
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;

    }
    var csrftoken = getToken('csrftoken');
</script>

{% endblock javascript %}
        
    
    



</body>
</html>

justpython/templates/footer.html
<footer class="footer bg-gray-100">
    
    
    
  <section class="section">
    <div class="container"> 
      <div class="content has-text-centered">
          
        <div class="sm:flex sm:items-center sm:justify-between">
            <div class="flex justify-center text-teal-300 sm:justify-middle">
             <img class="rounded-full" src="https://static.thenounproject.com/png/2686167-84.png" width="40" height="40" />
             <div class="flex justify-center text-teal-300 sm:justify-start">
              <img class="rounded-full" src="https://www.svgrepo.com/show/494273/facebook-round.svg" width="25" height="25" />
              <img class="rounded-full" src="https://www.svgrepo.com/show/494278/linkedin-round.svg" width="25" height="25" />
              <a href="https://www.linkedin.com/in/sudarshan-mestha/">
                <img class="rounded-full" src="https://www.svgrepo.com/show/494277/instagram-round.svg" width="25" height="25" />
              </a>
            </div>
            </div>
      
            
        </div>
        <p class="mt-4 text-sm text-center text-gray-400 lg:text-middle">
          T&C &nbsp; Career &nbsp; Privacy & Policy &nbsp; Developers
        </p>
          <p>
            Copyright &copy;
            <script>document.write(new Date().getFullYear());</script>
            All rights reserved | This website is made with <i class="fas fa-heart"></i>
          </p>
  
          
         
    </div>  
    </div>
  </section>

  
</footer>

justpython/templates/navbar.html
<div class="max-w-8xl mx-auto sm:px-4 lg-px-8">
  <nav id="navbar" class="navbar">
    <div class="container">
  
        <div class="navbar-brand">
            <a class="navbar-item flex items-center flex-shrink-0 mr-6" href="{% url 'home' %}">
                <span class="font-semibold text-xl tracking-tight">JustPython</span>
            </a>
            <span class="navbar-burger burger" data-target="navbarMenu">
                                <span></span>
                                <span></span>
                                <span></span>
                                 
            </span>
        </div>
  
        <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-end">
  
                <div class="navbar-item">
                       <form method="get" action="/"> 
                        <div class="control has-icons-left">
                            <input class="input is-rounded" name="query" type="text" placeholder="Search">
                            <span class="icon is-left">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                       </form>
                        
               
                </div>
  
                <a href="{% url 'home' %}" class="navbar-item is-active is-size-5 has-text-weight-semibold">
                    Home
                </a>
                <a href="{% url 'topic:topic-list' %}" class="navbar-item is-size-5 has-text-weight-semibold">
                    Blog
                </a>
                <a href="{% url 'content:course-list' %}" class="navbar-item is-size-5 has-text-weight-semibold">
                    Courses
                </a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'users:detail' request.user.username  %}" class="navbar-item is-size-5 has-text-weight-semibold">
                  My Profile
                </a>
  
                <a href="{% url 'account_logout' %}" class="navbar-item is-size-5 has-text-weight-semibold">
                  Logout
                </a>
                {% endif %}
                {% if not request.user.is_authenticated %}
            <a href="{% url 'account_login' %}" class="navbar-item is-size-5 has-text-weight-semibold">
              Login
            </a>
            {% endif %}
            </div>
        </div>
        
    </div>
  </nav>
</div>




    

 
 {% comment %}
 <nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler navbar-toggler-right"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">inupcookie</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">Item</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link"
               href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
          </li>
        {% else %}
          {% if ACCOUNT_ALLOW_REGISTRATION %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
            </li>
          {% endif %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
 {% endcomment %}
  